name: Run Cypress Tests

# Trigger the workflow on push to main or develop branches
on:
  push:
    branches:
      - main
      - develop  # You can add more branches here if needed

jobs:
  test:
    runs-on: ubuntu-latest

    # Steps to set up the environment and run tests
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Or the version that you're using

    - name: Install dependencies
      run: |
        npm install  # Ensure Cypress and all dependencies are installed

    - name: Run Cypress tests (Feature files only)
      run: |
        # Run all feature files in the 'e2e' directory
        npx cypress run --spec 'cypress/e2e/**/*.feature' --env environment=${{ github.ref }}

    - name: Upload test results and videos/screenshots (optional)
      if: always()  # Ensures this step runs even if tests fail
      run: |
        mkdir -p artifacts/videos
        mkdir -p artifacts/screenshots
        cp -r cypress/videos artifacts/videos
        cp -r cypress/screenshots artifacts/screenshots

    - name: Upload Cypress artifacts to GitHub
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: cypress-artifacts
        path: artifacts/
