name: Run Cypress Tests

# Trigger the workflow on push to master branch
on:
  push:
    branches:
      - master  # You can add other branches if needed

jobs:
  test:
    runs-on: ubuntu-latest

    # Steps to set up the environment and run tests
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # You can adjust the version if needed

    - name: Install dependencies
      run: |
        npm install  # Ensure Cypress and all dependencies are installed

    - name: Run Cypress tests (Feature files only)
      run: |
        npx cypress run --spec 'cypress/e2e/**/*.feature' --env environment=${{ github.ref }}

    # Optionally, you can add a step to log the result of the tests (pass/fail status)
    - name: Display test result
      run: |
        if [ $? -eq 0 ]; then echo "Cypress tests passed"; else echo "Cypress tests failed"; exit 1; fi
